### ISSUE TITLE
Why gatherpoint kernel need a graduate function?

### ISSUE THREAD

**Issue by usherbob** [charlesq34/pointnet2#133]
I believe there is no parameter in `gather point` operation, the input is xyz,  samplig index, and the output is gathered points. Why we need a  `gather_point_grad` operation here?

**Comment by usherbob** [comment]
Ha, I figured it out. It needs the gather_point_grad operation because it needs backprop the gradient. Just like max-pool needs a gradient method.

**Comment by yiakwy** [comment]
@usherbob like "max_pooling", there is no gradient with for operator "group_point" because this is a non-parametric operator, i.e., unlike bachtnorm, convolution, there is no parameters affecting the final output.

However when referring to grad, we are actually talking about two things, parameters in this layer and output values for this operator.

The operator has output value $$a^{l}_i = activate (z^{l}_i)$$ where z is going to operator i in layer l. When grad is passed as input, the difference of error J w.r.t the z, is computed as:

> $$ \theta^{l}_i = dJ/dz = activate_grad(z^{l}_i) * sum{\theta^{l+1}_j * w_{ij}}  $$

Which means only connected values have an identical gradient. Hence we need select value indices we assigned from and assign gradients back.
