### ISSUE TITLE
Import network module (No module named model) Scannet

### ISSUE THREAD

**Issue by OmarAhmadien** [charlesq34/pointnet2#78]
What is the model to be used with scene segmentation code?
I got this error. Any suggestions?

`  File "train.py", line 48, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "XXXX/miniconda3/envs/tensorflow/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named model
`

**Comment by OmarAhmadien** [comment]
I solved this by adding this line:
`sys.path.append(os.path.join(ROOT_DIR, 'models'))`
after line 14.

and changing the parser from: `parser.add_argument('--model', default='model', help='Model name [default: model]')`

To:

`parser.add_argument('--model', default='pointnet2_sem_seg', help='Model name [default: model]')`

**Comment by OmarAhmadien** [comment]
> I solved this by adding this line:
> `sys.path.append(os.path.join(ROOT_DIR, 'models'))`
> after line 14.
> 
> and changing the parser from: `parser.add_argument('--model', default='model', help='Model name [default: model]')`
> 
> To:
> 
> `parser.add_argument('--model', default='pointnet2_sem_seg', help='Model name [default: model]')`

No further problems regarding that issue.

**Comment by NicksonYap** [comment]
I faced the same error for `part_seg` turns out  (as of 42926632a3c33461aebfbee2d829098b30a23aaa)
I was able to solve this error by running:

```
cd part_seg
python train.py --model pointnet2_sem_seg
```

Note:
However I was facing another error:
```
Executor failed to create kernel. Not found: No registered '_CopyFromGpuToHost'
```
Related: https://github.com/tensorflow/tensorflow/issues/22134
Seems to be issue regarding batch size (I was simultaneously training PointNet v1)
Will try again later

Edit: it's indeed due to batch size, out of ram https://github.com/charlesq34/pointnet2/issues/80
